
# -------------------------- DEFINING GLOBAL VARIABLES -------------------------
PALETTE_DARKEST = '#191919'
PALETTE_DARK = '#750E21'
PALETTE_LIGHT = '#E3651D'
PALETTE_LIGHTEST = '#BED754'

#
# NAVY_BLUE = '#05445E'
# BLUE_GROTTO = '#189AB4'
# BLUE_GREEN = '#75E6DA'
# BABY_BLUE = '#D4F1F4'
#
# F_BACKGROUND_1 = '#FF6C22'
# F_BACKGROUND_2 = '#F5E8C7'
# F_BACKGROUND_3 = '#2B3499'
# F_BACKGROUND_4 = '#557C55'
# F_BACKGROUND_5 = '#427D9D'
# F_BACKGROUND_6 = '#190482'

THEME_COLOR = 'blue'
# THEME_COLOR = '#748cb3'
# TEXT_COLOR = '#0cb3f0'
TEXT_COLOR = 'black'

# MAIN_BACKGROUND_COLOR = 'blue'
# ICON_BACKGROUND_COLOR = 'yellow'
# SIDEBAR_BACKGROUND_COLOR = 'green'
# SELECTION_BACKGROUND_COLOR = 'yellow'
# HEADER_BACKGROUND_COLOR = 'red'
# # MAIN_BACKGROUND_COLOR = '#748cb3'
# BRANDING_BACKGROUND = 'pink'

ICON_BACKGROUND_COLOR = PALETTE_DARK
SIDEBAR_BACKGROUND_COLOR = PALETTE_LIGHT
SELECTION_BACKGROUND_COLOR = PALETTE_DARKEST
HEADER_BACKGROUND_COLOR = PALETTE_DARK
MAIN_BACKGROUND_COLOR = PALETTE_LIGHT
BRANDING_BACKGROUND = PALETTE_DARK

APP_WIDTH = 1200
APP_HEIGHT = 750

SIDEBAR_WIDTH = 200
SIDEBAR_HEIGHT = 1000
APP_FRAME_WIDTH = APP_WIDTH - SIDEBAR_WIDTH
APP_FRAME_HEIGHT = 600

U_WIDTH = APP_FRAME_WIDTH - 150
U_HEIGHT = APP_FRAME_HEIGHT - 250

BRAND_FRAME_HEIGHT = 100

STATUS_FRAME_WIDTH = APP_FRAME_WIDTH - 40
STATUS_FRAME_HEIGHT = BRAND_FRAME_HEIGHT

CONTROLS_FRAME_WIDTH = APP_FRAME_WIDTH
CONTROLS_FRAME_HEIGHT = 30

COMMANDS_WIDTH = 250

SELECTION_WIDTH = APP_WIDTH - SIDEBAR_WIDTH
SELECTION_HEIGHT = 100

W_ICON = './images/pngtree-pdf-file-icon-png-png-image_4899509.jpeg'


PDF_IMG_DIR = f'./pdf_files/pdf_images'
PAGES_DIR = f'./pdf_files/pdf_pages'
COMBO_DIR = f'./pdf_files/pdf_combo'

ICON_IMG = './images/icons/icons8-batman-color/icons8-batman-144.png'
DIR_IMG = './images/icons8-folder-48.png'
LIST_IMG = './images/icons8-pdf-48.png'


